spring:
  data:
    mongodb:
      uri: ${MONGO_DB_URI_DEV}
      database: ${MONGO_DB_NAME_DEV}
    redis:
      url: ${REDIS_URL_DEV}
  rabbitmq:
    host: ${RABBIT_MQ_HOST_DEV}
    port: ${RABBIT_MQ_PORT_DEV}
    username: ${RABBIT_MQ_USERNAME_DEV}
    password: ${RABBIT_MQ_PASSWORD_DEV}

server:
  address: 0.0.0.0

crazypoint:
  cache-management:
    clear-cache-on-start: true
  bigo-live:
    user-updates-check-enabled: false