spring:
  application:
    name: CrazyPoint
  profiles:
    active: ${CRAZY_POINT_ACTIVE_PROFILE}
  data:
    mongodb:
      auto-index-creation: true

server:
  port: ${PORT:8080}
  servlet:
    encoding:
      force-response: true
      charset: UTF-8

crazypoint:
  exception-generator:
    string-unit-exception-probability-percent: 10
  web:
    private-access:
      username: ${CRAZY_POINT_WEB_ACCESS_USERNAME}
      password: ${CRAZY_POINT_WEB_ACCESS_PASSWORD}
    rest:
      api-info:
        title: CrazyPoint API
        version: 0.0.1
        author-email: feodor.kekovich@gmail.com
      endpoints:
        public:
          ping: /api/public/ping
          bigo-official-user-info: /api/public/bigo/official/user/info
          string-remove-dashes: /api/public/string/remove_dashes
          string-to-upper-case: /api/public/string/to_upper_case
          string-reverse: /api/public/string/reverse
        private:
          bigo-user-create: /api/private/bigo/internal/user/create
          bigo-user-update: /api/private/bigo/internal/user/update
          bigo-user-delete: /api/private/bigo/internal/user/delete
          bigo-user-start-stream: /api/private/bigo/internal/user/start_stream
          bigo-user-end-stream: /api/private/bigo/internal/user/end_stream
          bigo-users-list: /api/private/bigo/internal/user/list
          bigo-user-show-stream-message: /api/private/bigo/internal/user/ssm
  bigo-live:
    user-updates-api-url: ${BIGO_LIVE_USER_UPDATES_API_URL}
    user-updates-check-delay-ms: 10000
    user-link-prefix: https://www.bigo.tv/user/
  donate-properties:
    donate-link: https://crazypoint.vip/donate
    belarus-bank:
      title: BelarusBank card
      card: 9112380175032152
      iban: BY56AKBB30340002088280070000
    sber-bank-belarus:
      title: SberBank card
      card: 5470874047539810
      iban: BY43BPSB3014F000000010097002
    pko-bank:
      title: PKOBank card (Visa)
      card: 4251250230037987
      account-number: 02102011270000180203850088
      iban: PL02102011270000180203850088
    yoo-money:
      title: YooMoney wallet
      wallet: 4100117004369583
    usd-t:
      title: USDT (TRC20)
      address: TA4uyqmmSXnRF8Z2UDQN1R4N1DkX88Ndk9
  social-links-properties:
    instagram:
      enabled: false
      title: Instagram
      link: https://www.instagram.com
    telegram:
      enabled: true
      title: Telegram
      link: https://t.me/pu3r41k
    tiktok:
      enabled: false
      title: TikTok
      link: https://tiktok.com
    bigo-live:
      enabled: true
      title: BigoLive
      link: https://www.bigo.tv/user/933831125

springdoc:
  swagger-ui:
    path: /swagger
    display-request-duration: true
    doc-expansion: none
  api-docs:
    path: /api-docs