spring:
  data:
    mongodb:
      uri: ${MONGO_DB_URI}
      database: ${MONGO_DB_NAME}
    redis:
      url: ${REDIS_URL}
  rabbitmq:
    host: ${RABBIT_MQ_HOST}
    port: ${RABBIT_MQ_PORT}
    username: ${RABBIT_MQ_USERNAME}
    password: ${RABBIT_MQ_PASSWORD}

crazypoint:
  cache-management:
    clear-cache-on-start: false
  bigo-live:
    user-updates-check-enabled: true