spring:
  profiles:
    active: ${CRAZY_POINT_ACTIVE_PROFILE}
  data:
    mongodb:
      auto-index-creation: true
  main:
    web-application-type: servlet
  web:
    locale: en

server:
  servlet:
    encoding:
      force-response: true
      charset: UTF-8

crazypoint:
  exception-generator:
    string-unit-exception-probability-percent: 10
  rabbit-mq-binding:
    bigo-user-start-stream-event-exchange-name: bigo-user-start-stream-event-exchange
    bigo-user-end-stream-event-exchange-name: bigo-user-end-stream-event-exchange
  web:
    private-access:
      username: ${WEB_ACCESS_USERNAME}
      password: ${WEB_ACCESS_PASSWORD}
    rest:
      api-info:
        title: CrazyPoint API
        version: 0.0.1
        author-email: feodor.kekovich@gmail.com
      endpoints:
        public:
          ping: /api/public/ping
          avatars-list: /api/public/avatar/list
          bigo-official-user-info: /api/public/bigo/official/user/info
          bigo-user-stream-chart-daily-data: /api/public/bigo/internal/user/stream_chart_daily
          bigo-user-stream-days-data: /api/public/bigo/internal/user/stream_days
          bigo-users-list: /api/public/bigo/internal/user/list
          string-remove-dashes: /api/public/string/remove_dashes
          string-to-upper-case: /api/public/string/to_upper_case
          string-reverse: /api/public/string/reverse
        private:
          avatar-create: /api/private/avatar/create
          avatar-delete: /api/private/avatar/delete
          bigo-user-create: /api/private/bigo/internal/user/create
          bigo-user-update: /api/private/bigo/internal/user/update
          bigo-user-delete: /api/private/bigo/internal/user/delete
          bigo-user-start-stream: /api/private/bigo/internal/user/start_stream
          bigo-user-end-stream: /api/private/bigo/internal/user/end_stream
          bigo-user-show-stream-message: /api/private/bigo/internal/user/ssm
  bigo-live:
    user-updates-api-url: ${BIGO_LIVE_USER_UPDATES_API_URL}
    user-updates-check-delay-ms: 10000
    user-link-prefix: https://www.bigo.tv/user/

springdoc:
  swagger-ui:
    path: /swagger
    display-request-duration: true
    doc-expansion: none
  api-docs:
    path: /api-docs